Mvc1_pro/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc1_pro.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public String Name { get; set; }
        public String Address { get; set; }
        public int Salary { get; set; }
    }
}

Mvc1_pro/Models/ErrorViewModel.cs
using System;

namespace Mvc1_pro.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Mvc1_pro/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc1_pro.Models
{
    public class Product
    {
        public int Id { get; set; }
        public String Name { get; set; }
        public int Price { get; set; }
    }
}

Mvc1_pro/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc1_pro.Models
{
    public class Student
    {
        public int Id
        {
            get;
            set;
        }
        public String Name { get; set; }
        public String City { get; set; }
        public int Marks { get; set; }
    }
}

Mvc1_pro/Controllers/EmpController.cs
using Microsoft.AspNetCore.Mvc;
using Mvc1_pro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc1_pro.Controllers
{
    public class EmpController : Controller
    {
        public IActionResult Emp_List()
        {
            List<Employee> emp = new List<Employee>()
          {
             new Employee{ Id=111,Name="AAA",Address="Pune",Salary=89000},
             new Employee{ Id=112,Name="LLL",Address="Mumbai",Salary=87000},
             new Employee{ Id=113,Name="MMM",Address="Delhi",Salary=34000},
             new Employee{ Id=114,Name="BBB",Address="Pune",Salary=123000},


          };
            ViewData["EmployeeList"]=emp;
            ViewBag.Employee =emp;
            return View();
        }
    }
}

Mvc1_pro/Controllers/FoodController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc1_pro.Controllers
{
    public class FoodController : Controller
    {
        [HttpGet]

        public IActionResult FoodMenu()
        {
            List<String> option = new List<String>() { "select option", "Veg", "Non veg" };
            ViewData["option"] = new SelectList(option);

            return View();
        }
        [HttpPost]
          public IActionResult FoodMenu(IFormCollection form,ICollection<String>food)
          {
              ViewBag.Name = form["fname"];
              ViewBag.Contact = form["contact"];
              ViewBag.FoodOrder = food;
              ViewBag.Option = form["option"];
              return View("FoodDetails");
          }
    
    }
}

Mvc1_pro/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Mvc1_pro.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc1_pro.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewBag.Message = "This is simple MVC Application";
            List<String> colorList = new List<string>()
            {
                "Blue","Red","Green","Pink","Yellow","Gray","White","Black"

            };
             ViewData["message"] = "This is my First MVC Page...";
            ViewData["Experience"] = "I Have 2 Years Experience";
            ViewData["Year"] = 2022;
            ViewData["list"] = colorList;
            ViewBag.ColorList = colorList;


            return View();
        }

        public IActionResult aboutus()
        {
            return View();
        }

        public IActionResult contactus()
        {
            return View();
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Mvc1_pro/Controllers/PersonController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc1_pro.Controllers
{
    public class PersonController : Controller
    {
        [HttpGet]
        public IActionResult PersonalDetails()
        {
            List<String> options = new List<string>() { "select option","yes","no"};
            ViewData["options"] = new SelectList(options);
            return View();
        }
        [HttpPost]
        public IActionResult PersonalDetails(IFormCollection form)
        {
            ViewBag.Name = form["fname"];
            ViewBag.Contact = form["contact"];
            ViewBag.Gender = form["gender"];
            ViewBag.Hobbies =form["hobbies"];
            ViewBag.Option = form["options"];
            return View("Details");
        }
    }
}

Mvc1_pro/Controllers/ProductController.cs
   using Microsoft.AspNetCore.Mvc;
using Mvc1_pro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc1_pro.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult List()
        {
            List<Product> product = new List<Product>()
            {
                new Product{ Id=1,Name="Dell Laptop",Price=12344},
                 new Product{ Id=2,Name="Lenovo Laptop",Price=44344},
                  new Product{ Id=3,Name="HP Laptop",Price=2223},
                   new Product{ Id=4,Name="Dell Mouse",Price=1234},
            };
            ViewData["productlist"] = product;
            ViewBag.Products = product;

            return View();
        }
    }
}

Mvc1_pro/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Mvc1_pro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc1_pro.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Stud_List()
        {
            List<Student> stud = new List<Student>()
          {
          new Student{ Id=101,Name="Siya",City="Pune",Marks=89},
          new Student{ Id=102,Name="Ashwini",City="Mumbai",Marks=99},
          new Student{ Id=103,Name="Swara",City="Delhi",Marks=78},
          new Student{ Id=104,Name="Riya",City="Chennai",Marks=76},
          new Student{ Id=105,Name="Radha",City="Pune",Marks=90},

          };
            ViewData["StudentList"] = stud;
            ViewBag.Student = stud;
            return View();
        }
    }
}

Mvc1_pro/Views/Emp/Emp_List.cshtml
@{
    ViewData["Title"] = "Emp_List";
}

<h1>Emp_List</h1>
<table class=" table table-bordered">
    <tr>
        <th>Employee Id</th>
        <th>Employee Name</th>
        <th>Employee Address</th>
        <th>Employee Salary</th>
    </tr>
    @foreach (Employee e in (IEnumerable<Employee>)ViewData["EmployeeList"])
    {
        <tr>
            <td>@e.Id</td>
            <td>@e.Name</td>
            <td>@e.Address</td>
            <td>@e.Salary</td>
        </tr>
    }
</table>

Mvc1_pro/Views/Food/FoodMenu.cshtml
@{
    ViewData["Title"] = "FoodMenu";
}

<h1>FoodMenu Details</h1>
@using (Html.BeginForm())
{
<table class="table">
    <tr>
        <td>
            @Html.Label("Enter Name:")
        </td>
        <td>
            @Html.TextBox("fname")
        </td>
    </tr>
    <tr>
        <td>
            @Html.Label("Enter Number:")
        </td>
        <td>
            @Html.TextBox("contact")
        </td>
    </tr>
    <tr>
        <td>
            @Html.Label("Select food order:")
        </td>
        <td>
            <input type="checkbox" name="food" value="Pizza">Pizza
            <input type="checkbox" name="food" value="Burger">Burger
            <input type="checkbox" name="food" value="Coffee">Coffee
            <input type="checkbox" name="food" value="Pasta">Pasta
        </td>
    </tr>
    <tr>
        <td>
            <label>select option</label>
        </td>
        <td>
            @Html.DropDownList("option")
        </td>
    </tr>

    <tr>
        <td>
        </td>
        <td>
            <input type="Submit" value="submit">
        </td>
    </tr>
</table>

}

Mvc1_pro/Views/Food/foodDetails.cshtml
@{
    ViewData["Title"] = "foodDetails";
}

<h1>Order Details</h1>

<p>
    Name:@ViewBag.Name
</p>
<p>
    Contact:@ViewBag.Contact
</p>
<p>
    <ul>
        @foreach (var item in ViewBag.FoodOrder)
        { 
        <li>
            @item
        </li>
        }

    </ul>
</p>
<p>
    Food Type:@ViewBag.Option
</p>

Mvc1_pro/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h3>
        @ViewData["message"]
</h3>
<p>
        @ViewData["Experience"]<small>@ViewData["year"]</small>
</p>
<ol>
        @foreach (String color in (IEnumerable<String>)ViewData["list"])
        { 
        <li>

            @color
            </li>
        }
</ol>

<ul>
    @foreach (var item in ViewBag.ColorList)
    { 
    <li>

        @item
        </li>
    }
 </ul>

Mvc1_pro/Views/Home/aboutus.cshtml
@{
    ViewData["Title"] = "aboutus";
}

<h1>aboutus</h1>

        Enter First Name: <input type="text" name="fname" /><br><br>
        Enter Lasr Name:<input type="text"name="lname"/><br><br>
        Enter Password:<input type="password" name="pass"><br><br>
        <input typt="submit" value="submit"/>

Mvc1_pro/Views/Home/contactus.cshtml
@{
    ViewData["Title"] = "contactus";
}

<h1>contactus</h1>

        Enter First Name:
<input type="text" name="fname" />
<br>
<br>
        Enter Lasr Name:
<input type="text" name="lname" />
<br>
<br>
        Enter Password:
<input type="password" name="pass">
<br>
<br>
select one option for know more:-
<br>
<input type="radio" id="html" name="fav_language" value="HTML">
<label for="html">HTML</label>
<br>
<input type="radio" id="css" name="fav_language" value="CSS">
<label for="css">CSS</label>
<br>
<input type="radio" id="javascript" name="fav_language" value="JavaScript">
<label for="javascript">JavaScript</label>
<br>

<input typt="submit" value="submit" />

Mvc1_pro/Views/Person/Details.cshtml
@{
    ViewData["Title"] = "Details";
}

<h1>Personal Details</h1>
<p>
    Name:@ViewBag.Name
</p>
<p>
    Contact:@ViewBag.Contact
</p>
<p>
    Gender:@ViewBag.Gender
</p>
<p>
    <ul>
        @foreach (var item in ViewBag.Hobbies)
        {

            @if (item != "false")
            {
            <li>
                @item
            </li>
            }
        }
        </ul>
</p>
<p>
    Your Option:@ViewBag.Option
</p>

Mvc1_pro/Views/Person/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

Mvc1_pro/Views/Person/PersonalDetails.cshtml
@{
    ViewData["Title"] = "PersonalDetails";
}

<h1>Personal  Details</h1>
@using (Html.BeginForm())
{
<table class="table">
    <tr>
        <td>
            @Html.Label("Enter Full Name")
        </td>
        <td>
            @Html.TextBox("fname")
        </td>
    </tr>
    <tr>
        <td>
            @Html.Label("Enter Contact:")
        </td>
        <td>
            @Html.TextBox("contact")
       </td>
    </tr>
    <tr>
        <td>
            @Html.Label("Select Gender:")
        </td>
        <td>
            @Html.RadioButton("gender", "Male")Male
            @Html.RadioButton("gender", "Female")FeMale
        </td>
    </tr>
    <tr>
        <td>
            <label>select option</label>
        </td>
        <td>
        @Html.DropDownList("options")
        </td>
    </tr>
    <tr>
        <td>
            @Html.Label("Select Hobbies:")
        </td>
        <td>
            @Html.CheckBox("hobbies", new { @value = "Sports" })Sport
            @Html.CheckBox("hobbies", new { @value = "Music" })Music
            @Html.CheckBox("hobbies", new { @value = "Reading" })Reading
           
        </td>
    </tr>
    <tr>
        <td>
        </td>
        <td>
            <input type="Submit" value="submit">
        </td>
    </tr>
</table>
}

Mvc1_pro/Views/Product/List.cshtml
@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<h1>Product List</h1>

<table class=" table table-bordered">
    <tr>
        <th>Product Id</th>
        <th>Product Name</th>
        <th>Product Price</th>
    </tr>
    @foreach (Product p in (IEnumerable<Product>)ViewData["productlist"])
    {
        <tr>
            <td>@p.Id</td>
            <td>@p.Name</td>
            <td>@p.Price</td>
        </tr>
    }
</table>


<h1>View Bag List</h1>

<table class=" table table-bordered">
    <tr>
        <th>Product Id</th>
        <th>Product Name</th>
        <th>Product Price</th>
    </tr>
    @foreach (Product p in ViewBag.Products)
    {
        <tr>
            <td>@p.Id</td>
            <td>@p.Name</td>
            <td>@p.Price</td>
        </tr>
    }
</table>

Mvc1_pro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mvc1_pro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mvc1_pro</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="List">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Stud_List">Student_List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emp" asp-action="Emp_List">Employee_List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="PersonalDetails">Personal Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="food" asp-action="FoodMenu">Food Details</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Mvc1_pro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Mvc1_pro/Views/Student/Stud_List.cshtml
@{
    ViewData["Title"] = "Stud_List";
}

<h1>Stud_List</h1>
<table class="table table-bordered">
    <tr>
        <th>Student Id</th>
        <th>Student Name</th>
        <th>Student City</th>
        <th>Student Marks</th>
    </tr>
    @foreach (Student s in (IEnumerable<Student>)ViewData["StudentList"])
    { 
    <tr>
        <td>@s.Id</td>
        <td>@s.Name</td>
        <td>@s.City</td>
        <td>@s.Marks</td>
    </tr>
    }
    </table>